require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FollowsController do

  # This should return the minimal set of attributes required to create a valid
  # Follow. As you add validations to Follow, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FollowsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all follows as @follows" do
      follow = Follow.create! valid_attributes
      get :index, {}, valid_session
      assigns(:follows).should eq([follow])
    end
  end

  describe "GET show" do
    it "assigns the requested follow as @follow" do
      follow = Follow.create! valid_attributes
      get :show, {:id => follow.to_param}, valid_session
      assigns(:follow).should eq(follow)
    end
  end

  describe "GET new" do
    it "assigns a new follow as @follow" do
      get :new, {}, valid_session
      assigns(:follow).should be_a_new(Follow)
    end
  end

  describe "GET edit" do
    it "assigns the requested follow as @follow" do
      follow = Follow.create! valid_attributes
      get :edit, {:id => follow.to_param}, valid_session
      assigns(:follow).should eq(follow)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Follow" do
        expect {
          post :create, {:follow => valid_attributes}, valid_session
        }.to change(Follow, :count).by(1)
      end

      it "assigns a newly created follow as @follow" do
        post :create, {:follow => valid_attributes}, valid_session
        assigns(:follow).should be_a(Follow)
        assigns(:follow).should be_persisted
      end

      it "redirects to the created follow" do
        post :create, {:follow => valid_attributes}, valid_session
        response.should redirect_to(Follow.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved follow as @follow" do
        # Trigger the behavior that occurs when invalid params are submitted
        Follow.any_instance.stub(:save).and_return(false)
        post :create, {:follow => {}}, valid_session
        assigns(:follow).should be_a_new(Follow)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Follow.any_instance.stub(:save).and_return(false)
        post :create, {:follow => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested follow" do
        follow = Follow.create! valid_attributes
        # Assuming there are no other follows in the database, this
        # specifies that the Follow created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Follow.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => follow.to_param, :follow => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested follow as @follow" do
        follow = Follow.create! valid_attributes
        put :update, {:id => follow.to_param, :follow => valid_attributes}, valid_session
        assigns(:follow).should eq(follow)
      end

      it "redirects to the follow" do
        follow = Follow.create! valid_attributes
        put :update, {:id => follow.to_param, :follow => valid_attributes}, valid_session
        response.should redirect_to(follow)
      end
    end

    describe "with invalid params" do
      it "assigns the follow as @follow" do
        follow = Follow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Follow.any_instance.stub(:save).and_return(false)
        put :update, {:id => follow.to_param, :follow => {}}, valid_session
        assigns(:follow).should eq(follow)
      end

      it "re-renders the 'edit' template" do
        follow = Follow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Follow.any_instance.stub(:save).and_return(false)
        put :update, {:id => follow.to_param, :follow => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested follow" do
      follow = Follow.create! valid_attributes
      expect {
        delete :destroy, {:id => follow.to_param}, valid_session
      }.to change(Follow, :count).by(-1)
    end

    it "redirects to the follows list" do
      follow = Follow.create! valid_attributes
      delete :destroy, {:id => follow.to_param}, valid_session
      response.should redirect_to(follows_url)
    end
  end

end
