require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VolunteersController do

  describe "GET index" do
    it "assigns all volunteers as @volunteers, ordered by name" do
      Volunteer.all.each &:destroy
      v1 = create :volunteer, :name => 'b'
      v2 = create :volunteer, :name => 'a'
      v3 = create :volunteer, :name => 'c'

      get :index
      assigns(:volunteers).should eq([v2, v1, v3])
    end
  end

  describe "GET show" do
    it "assigns the requested volunteer as @volunteer" do
      volunteer = create :volunteer
      get :show, :id => volunteer.id
      assigns(:volunteer).should eq(volunteer)
    end
  end

  describe "GET new" do
    it "assigns a new volunteer as @volunteer" do
      get :new
      assigns(:volunteer).should be_a_new(Volunteer)
    end
  end

  describe "GET edit" do
    before :each do
      @volunteer = log_in_as :volunteer
    end

    it "assigns the requested volunteer as @volunteer" do
      volunteer = create :volunteer
      get :edit, :id => volunteer.id
      assigns(:volunteer).should eq(volunteer)
    end

    it "requires the user to be the volunteer" do
      log_in_as :volunteer
      get :edit, :id => @volunteer.id
      response.should redirect_to(root_url)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Volunteer" do
        expect {
          post :create, :volunteer => attributes_for(:volunteer)
        }.to change(Volunteer, :count).by(1)
      end

      it "assigns a newly created volunteer as @volunteer" do
        post :create, :volunteer => attributes_for(:volunteer)
        assigns(:volunteer).should be_a(Volunteer)
        assigns(:volunteer).should be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved volunteer as @volunteer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volunteer.any_instance.stub(:save).and_return(false)
        post :create, :volunteer => {}
        assigns(:volunteer).should be_a_new(Volunteer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volunteer.any_instance.stub(:save).and_return(false)
        post :create, :volunteer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    before :each do
      @volunteer = log_in_as :volunteer
    end

    describe "with valid params" do
      it "updates the requested volunteer" do
        # Assuming there are no other volunteers in the database, this
        # specifies that the Volunteer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Volunteer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => @volunteer.to_param, :volunteer => {'these' => 'params'}
      end

      it "assigns the requested volunteer as @volunteer" do
        put :update, :id => @volunteer.to_param, :volunteer => attributes_for(:volunteer)
        assigns(:volunteer).should eq(@volunteer)
      end

      it "redirects to the volunteer" do
        put :update, :id => @volunteer.to_param, :volunteer => attributes_for(:volunteer)
        response.should redirect_to(@volunteer)
      end

      it "requires the user to be the volunteer" do
        log_in_as :volunteer
        put :update, :id => @volunteer.to_param, :volunteer => attributes_for(:volunteer)
        response.should redirect_to(root_url)
      end
    end

    describe "with invalid params" do
      it "assigns the volunteer as @volunteer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volunteer.any_instance.stub(:save).and_return(false)
        put :update, :id => @volunteer.to_param, :volunteer => attributes_for(:volunteer)
        assigns(:volunteer).should eq(@volunteer)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volunteer.any_instance.stub(:save).and_return(false)
        put :update, :id => @volunteer.to_param, :volunteer => attributes_for(:volunteer)
        response.should render_template("edit")
      end
    end
  end

end
